### ISSUE TITLE
Support for Non-localhost Usage

### ISSUE THREAD

**Issue by kkretsch** [EasyDynamics/oscal-editor-deployment#48]
As a user of the OSCAL Editor All-in-One Docker deployment, I want the UI to support a backend URL other than `localhost` so that I can access the UI from a device other than the one running the container.

### Acceptance Criteria
- The container can be run on one machine and the UI can be accessed from another machine

### Original Issue Report

I have a two PC setup where the linux workstation runs the docker stuff and one windows PC where I access via browser the docker offered services.
At least the start page of this editor shows up, but then fails to load the oscal files from the folder.
In the browser networking I can see that the web stuff is loaded from my private IP range where the docker is running, but the API seems hardcoded to use localhost as a target.

As the other folders can already be optionally defined by docker environment variables, it should be handled the same way for the API mountpoint. And it should be mentioned in the READMEs, that it is currently not possible to use it outside of localhost browser access.

Example request of the web stuff (working):
![image](https://user-images.githubusercontent.com/1115638/156726172-879f826a-2678-4150-8357-7c4335901067.png)

And the failing API request afterwards:
![image](https://user-images.githubusercontent.com/1115638/156726235-ae3d6364-3bd6-4eaa-bc79-75252ee0b920.png)

**Comment by kylelaker** [comment]
Thanks for this report! I think this stems from the way the Viewer application is built. We specify the URL of the REST service as an environment variable during the build process; because the environment state is converted to a static JavaScript object during the build, we can't (currently) modify that value during runtime.

As a first step to fix this (within this bundled container image), we can set the configuration value to use a _relative_ URL `/oscal/v1` rather than including the host. This should work fine for the `all-in-one` container image.

In the longer term, we'll want to look into a means to actually configure the viewer application at runtime to support various backends (so that it doesn't have to be rebuilt for every backend). Then we'll want to find a way to make it easier to set that value when running the container.

**Comment by kylelaker** [comment]
With #49 having been merged, the `latest` image should now work in an environment where the container is running on one machine and being accessed from another. @kkretsch before we close this, does the change that we've made properly support your use case?

**Comment by kkretsch** [comment]
Yes, I just updated the image and can now access the oscal files of the installation. Great idea to just use a relative path.
